<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AdvancedOrderManager</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdvancedOrderManager.Application\AdvancedOrderManager.Application.vbproj" />
    <ProjectReference Include="..\AdvancedOrderManager.Domain\AdvancedOrderManager.Domain.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
